import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";
import tseslint from "typescript-eslint";

const __dirname = dirname(fileURLToPath(import.meta.url));
const compat = new FlatCompat({ baseDirectory: __dirname });

export default tseslint.config(
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "src/components/ui/**", // shadcn-generated primitives
      "playwright-report/**",
      "test-results/**",
      "next-env.d.ts", // generated by Next on every build
    ],
  },

  // `next/core-web-vitals` already registers the jsx-a11y plugin, so adding
  // jsxA11y.flatConfigs.recommended on top throws "Cannot redefine plugin".
  // The stricter a11y rules are enabled by name below instead.
  ...compat.extends("next/core-web-vitals"),
  ...tseslint.configs.strictTypeChecked,

  {
    rules: {
      "jsx-a11y/alt-text": "error",
      "jsx-a11y/anchor-has-content": "error",
      "jsx-a11y/anchor-is-valid": "error",
      "jsx-a11y/aria-props": "error",
      "jsx-a11y/aria-proptypes": "error",
      "jsx-a11y/aria-unsupported-elements": "error",
      "jsx-a11y/click-events-have-key-events": "error",
      // NOT enabling control-has-associated-label: it cannot follow htmlFor
      // across JSX siblings and false-positives on every visually-hidden input
      // with an adjacent label. It is off in jsx-a11y's own recommended set for
      // that reason. label-has-associated-control below is the rule that
      // actually catches unlabelled fields.
      "jsx-a11y/heading-has-content": "error",
      "jsx-a11y/interactive-supports-focus": "error",
      // The single rule that would have caught the old app's biggest form
      // defect: placeholder-as-label on every input in Login/Register/NewForm.
      "jsx-a11y/label-has-associated-control": "error",
      "jsx-a11y/no-autofocus": "warn",
      "jsx-a11y/no-noninteractive-element-interactions": "error",
      "jsx-a11y/no-redundant-roles": "error",
      "jsx-a11y/role-has-required-aria-props": "error",
      "jsx-a11y/role-supports-aria-props": "error",
    },
  },

  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: __dirname,
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      // Prisma returns plenty of `any`-adjacent shapes; keep these as errors but
      // allow explicit narrowing rather than silent suppression.
      "@typescript-eslint/no-misused-promises": [
        "error",
        { checksVoidReturn: { attributes: false } },
      ],
      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true },
      ],
    },
  },

  // ─────────────────────────────────────────────────────────────
  // Architectural invariant #1: no Prisma access outside src/server/repos.
  //
  // The old app's IDOR (GET /api/jobs/:id read any user's row) existed because
  // ownership scoping was applied per-query by hand and one query forgot. Repos
  // take a TenantCtx first argument and splice companyId into every `where`;
  // this rule is what stops the pattern from being bypassed.
  // ─────────────────────────────────────────────────────────────
  {
    files: ["src/**/*.{ts,tsx}"],
    ignores: ["src/server/repos/**", "src/server/db.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "@/server/db",
              message:
                "Direct Prisma access is only allowed in src/server/repos/. Add or reuse a repo function that takes a TenantCtx and scopes by companyId.",
            },
            {
              name: "@prisma/client",
              importNames: ["PrismaClient"],
              message:
                "Instantiate PrismaClient only in src/server/db.ts. Import types from @prisma/client freely.",
            },
          ],
        },
      ],
    },
  },

  // ─────────────────────────────────────────────────────────────
  // Architectural invariant #2: process.env is read only in src/lib/env.ts,
  // which validates it with Zod and throws at boot. A missing CHAPA_SECRET_KEY
  // must fail the deploy, not surface as a 500 inside a customer's checkout.
  // ─────────────────────────────────────────────────────────────
  {
    files: ["src/**/*.{ts,tsx}"],
    // middleware.ts runs in the Edge runtime, where importing the full server
    // env schema would force validation of secrets (S3, Resend, Chapa) that are
    // neither available nor needed there. It reads only NODE_ENV.
    ignores: ["src/lib/env.ts", "src/middleware.ts"],
    rules: {
      "no-restricted-properties": [
        "error",
        {
          object: "process",
          property: "env",
          message:
            "Import the validated `env` from @/lib/env instead of reading process.env directly.",
        },
      ],
    },
  },

  // Root config files aren't part of the tsconfig project graph, so type-aware
  // rules can't resolve them. Lint them without type information.
  {
    files: ["*.mjs", "*.js", "*.config.*"],
    extends: [tseslint.configs.disableTypeChecked],
  },

  // Tests assert non-nullness explicitly (expect(x).not.toBeNull()) and then
  // use the value; a non-null assertion after that is clearer than optional
  // chaining that would silently pass on null.
  {
    files: ["src/**/*.test.ts", "src/**/*.test.tsx", "src/e2e/**/*.ts"],
    rules: {
      "@typescript-eslint/no-non-null-assertion": "off",
      "no-restricted-imports": "off",
    },
  },

  // Scripts that run outside the app runtime: they legitimately read
  // process.env and talk to Prisma directly.
  {
    files: ["prisma/**/*.ts", "src/e2e/**/*.ts", "scripts/**/*.ts"],
    rules: {
      "no-restricted-properties": "off",
      "no-restricted-imports": "off",
      "no-console": "off",
    },
  },
);
